#!/usr/bin/env python3
"""Generate diminished and augmented chord voicings for all 12 chromatic roots.

Algorithmically generates all practical guitar voicings by enumerating valid
fret combinations on standard string groups. Produces the same inversion
structure as PDF-extracted major/minor/dominant data:
  - One chord tone per string (no repeated pitch classes)
  - All inversions covered for each string group
  - Consistent string groupings with playable fret spans

Two families of output files:
  {root}_diminished.json  — types: dim, dim7 (full + partial), m7b5 (full + partial)
  {root}_augmented.json   — types: aug, aug7 (full + partial), aug9 (partial 4-note)

All dependencies are inlined — no external packages or project modules required.
Requires Python 3.8+.

Chord types
-----------
| Type  | Tones           | Notes |
|-------|-----------------|-------|
| dim   | R, b3, d5       | Diminished triad |
| dim7  | R, b3, d5, d7   | Fully diminished 7th |
| m7b5  | R, b3, d5, m7   | Half-diminished |
| aug   | R, M3, #5       | Augmented triad |
| aug7  | R, M3, #5, m7   | Augmented dominant 7th |
| aug9  | R, M9, M3, #5, m7 | Augmented dominant 9th (partial only) |

Full voicings use all chord tones. Partial voicings omit the root (recorded
in ``omitted_chord_tones``), enabling tighter jazz voicings.

Usage
-----
    # Generate to ./output/ directory:
    python3 generate_inversions.py

    # Custom output directory:
    python3 generate_inversions.py --output /path/to/dir

    # Print per-chord-type counts:
    python3 generate_inversions.py --summary

    # Quiet (no progress output):
    python3 generate_inversions.py -q
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from itertools import permutations, product
from pathlib import Path


# ---------------------------------------------------------------------------
# Music theory constants (inlined from extractor/notes.py)
# ---------------------------------------------------------------------------

CHROMATIC: list[str] = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
]

# String number → pitch class of open string
# String 6 = low E (E = pitch class 4), String 1 = high e (same)
_OPEN_STRINGS: dict[int, int] = {6: 4, 5: 9, 4: 2, 3: 7, 2: 11, 1: 4}

_ORDINALS: dict[int, str] = {
    6: "6th", 5: "5th", 4: "4th", 3: "3rd", 2: "2nd", 1: "1st"
}

# Chord tone palettes: intervals above root in semitones.
# Only the types generated by this script are included.
_CHORD_TONES: dict[str, list[int]] = {
    "dim":   [0, 3, 6],
    "dim7":  [0, 3, 6, 9],
    "m7b5":  [0, 3, 6, 10],
    "m6_9":  [0, 2, 3, 7, 9],
    "aug":   [0, 4, 8],
    "aug7":  [0, 4, 8, 10],
    "aug9":  [0, 2, 4, 8, 10],
}

# Flat-to-sharp enharmonic map for root normalisation.
_ENHARMONICS: dict[str, str] = {
    "Bb": "A#", "Eb": "D#", "Ab": "G#",
    "Db": "C#", "Gb": "F#", "Cb": "B", "Fb": "E",
}


def note_from_fret(string_num: int, fret: int) -> str:
    """Return the note name for a given string and absolute fret position."""
    return CHROMATIC[(_OPEN_STRINGS[string_num] + fret) % 12]


def validate_chord(notes: list[str], root: str, chord_type: str) -> tuple[bool, set[str]]:
    """Return (is_valid, expected_note_set) for a played chord.

    Notes that are an enharmonic spelling of an expected chord tone are treated
    as valid (e.g. Bb = A# for an A#-rooted chord).
    """
    intervals = _CHORD_TONES.get(chord_type, [])
    if not intervals:
        return False, set()
    normalized_root = _ENHARMONICS.get(root, root)
    if normalized_root not in CHROMATIC:
        return False, set()
    root_idx = CHROMATIC.index(normalized_root)
    expected = {CHROMATIC[(root_idx + i) % 12] for i in intervals}
    played = {n for n in notes if n != "x"}
    return played.issubset(expected), expected


def strict_chord_tones(root: str, chord_type: str) -> set[str]:
    """Return the canonical note set for omitted_chord_tones computation."""
    intervals = _CHORD_TONES.get(chord_type, [])
    normalized_root = _ENHARMONICS.get(root, root)
    if normalized_root not in CHROMATIC:
        return set()
    root_idx = CHROMATIC.index(normalized_root)
    return {CHROMATIC[(root_idx + i) % 12] for i in sorted(set(intervals))}


# ---------------------------------------------------------------------------
# Transposition (inlined from extractor/transpose.py)
# ---------------------------------------------------------------------------

def _transpose_diagram(diagram: dict, delta: int, new_root: str) -> dict:
    """Return a copy of *diagram* transposed by *delta* semitones.

    Open-string avoidance:
      Transpose down (delta < 0): if the lowest fret would drop below 1, shift
      all notes up 12 frets (one octave) to keep the voicing closed.
      Transpose up (delta > 0): if the source sits at fret 12 (to avoid an
      open-string voicing) and the result would exceed fret 12, shift back
      down by 12.
    """
    notes = diagram["notes"]
    src_starting = diagram["starting_fret"]

    raw_frets = [n["fret"] + delta for n in notes]
    new_starting = src_starting + delta

    if delta < 0:
        if new_starting < 1:
            raw_frets = [f + 12 for f in raw_frets]
            new_starting = src_starting + delta + 12
    elif delta > 0:
        if src_starting == 12 and new_starting > 12:
            raw_frets = [f - 12 for f in raw_frets]
            new_starting = src_starting + delta - 12

    new_notes = [
        {
            "string":    n["string"],
            "fret":      raw_frets[i],
            "note_name": note_from_fret(n["string"], raw_frets[i]),
            "finger":    n["finger"],
        }
        for i, n in enumerate(notes)
    ]

    chord_type = diagram["chord_type"]
    note_names = [n["note_name"] for n in new_notes]
    if new_root and chord_type and note_names:
        is_valid, expected = validate_chord(note_names, new_root, chord_type)
        played = set(note_names)
        strict = strict_chord_tones(new_root, chord_type)
        omitted = sorted(strict - played, key=lambda n: CHROMATIC.index(n))
        outside = sorted(
            played - expected,
            key=lambda n: CHROMATIC.index(n) if n in CHROMATIC else 0,
        )
    else:
        is_valid, omitted, outside = False, [], []

    return {
        **diagram,
        "root":                new_root,
        "starting_fret":       new_starting,
        "notes":               new_notes,
        "valid":               is_valid,
        "omitted_chord_tones": omitted,
        "outside_palette":     outside,
        "fret_correction":     None,
    }


# ---------------------------------------------------------------------------
# Generation constants
# ---------------------------------------------------------------------------

# Chromatic roots used for generation (sharps).
_CHROMATIC_ROOTS: list[str] = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
]

# Chord families → types
_FAMILIES: dict[str, list[str]] = {
    "diminished": ["dim", "dim7", "m7b5"],
    "augmented":  ["aug", "aug7", "aug9"],
}

# 3-string groups (adjacent + spread), matching major-triad groupings
_GROUPS_3: list[list[int]] = [
    [6, 5, 4], [5, 4, 3], [4, 3, 2], [3, 2, 1],           # adjacent
    [6, 5, 3], [6, 4, 3], [5, 4, 2], [5, 3, 2], [4, 3, 1], [4, 2, 1],  # spread
]

# 4-string groups, matching maj7 groupings
_GROUPS_4: list[list[int]] = [
    [6, 5, 4, 3], [6, 4, 3, 2], [5, 4, 3, 2], [5, 3, 2, 1], [4, 3, 2, 1],
]

_MAX_SPAN  = 5   # max fret span among fretted notes
_MAX_FRET  = 15  # highest allowed individual fret
_MAX_START = 12  # highest allowed starting fret for fully-fretted voicings


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _chord_tones_for(root: str, chord_type: str) -> list[str]:
    """Return ordered unique chord tones for root + chord_type."""
    root_idx = CHROMATIC.index(root)
    return [CHROMATIC[(root_idx + i) % 12] for i in sorted(set(_CHORD_TONES[chord_type]))]


def _string_category(string_nums: list[int]) -> str:
    """Human-readable string-group label, e.g. '2nd,3rd&4thStrings'."""
    s = sorted(string_nums)
    parts = [_ORDINALS[x] for x in s]
    if len(parts) == 1:
        return parts[0] + "String"
    return ",".join(parts[:-1]) + "&" + parts[-1] + "Strings"


def _inversion_label(notes: list[dict], root: str, chord_type: str) -> str:
    """Determine inversion from the bass note (highest string number = lowest pitch)."""
    intervals = sorted(set(_CHORD_TONES.get(chord_type, [])))
    root_idx = CHROMATIC.index(root)
    tone_seq = [CHROMATIC[(root_idx + i) % 12] for i in intervals]
    bass = max(notes, key=lambda n: n["string"])["note_name"]
    if bass not in tone_seq:
        return "Root Position"
    idx = tone_seq.index(bass)
    labels = ["Root Position", "1st Inversion", "2nd Inversion",
              "3rd Inversion", "4th Inversion"]
    return labels[min(idx, len(labels) - 1)]


# ---------------------------------------------------------------------------
# Core voicing generator
# ---------------------------------------------------------------------------

def _generate_voicings(
    chord_type: str,
    string_group: list[int],
    tones: list[str],
    root: str,
) -> list[dict]:
    """Enumerate all valid voicings for *tones* on *string_group*.

    Each string is assigned exactly one tone (via permutations). A voicing
    is kept when fretted notes span ≤ _MAX_SPAN frets, all frets ≤ _MAX_FRET,
    and at least one string is fretted.

    Returns diagram dicts with diagram_index=0 (caller should reassign).
    """
    if len(tones) != len(string_group):
        return []

    results: list[dict] = []
    seen: set[tuple[int, ...]] = set()

    for perm in permutations(tones):
        fret_options: list[list[int]] = []
        skip = False
        for s, tone in zip(string_group, perm):
            tone_idx = CHROMATIC.index(tone)
            base = (tone_idx - _OPEN_STRINGS[s]) % 12
            # Offer open (fret 0) and closed (fret 12) for strings where the
            # open pitch matches the chord tone.
            candidates = [f for f in (base, base + 12) if f <= _MAX_FRET]
            if not candidates:
                skip = True
                break
            fret_options.append(candidates)
        if skip:
            continue

        for combo in product(*fret_options):
            if combo in seen:
                continue
            fretted = [f for f in combo if f > 0]
            if not fretted:
                continue  # all-open degenerate
            if max(fretted) - min(fretted) > _MAX_SPAN:
                continue
            if not any(f == 0 for f in combo) and min(fretted) > _MAX_START:
                continue  # impractically high closed position

            seen.add(combo)
            notes: list[dict] = [
                {
                    "string":    s,
                    "fret":      f,
                    "note_name": note_from_fret(s, f),
                    "finger":    None,
                }
                for s, f in zip(string_group, combo)
            ]
            notes.sort(key=lambda n: -n["string"])

            played = {n["note_name"] for n in notes}
            _valid, expected = validate_chord(list(played), root, chord_type)
            strict = strict_chord_tones(root, chord_type)
            omitted = sorted(strict - played, key=lambda n: CHROMATIC.index(n))
            non_zero = [n["fret"] for n in notes if n["fret"] > 0]

            results.append({
                "page_number":         None,
                "diagram_index":       0,
                "chord_type":          chord_type,
                "category":            _string_category(string_group),
                "inversion_label":     _inversion_label(notes, root, chord_type),
                "starting_fret":       min(non_zero),
                "root":                root,
                "notes":               notes,
                "valid":               True,
                "omitted_chord_tones": omitted,
                "outside_palette":     [],
                "substitution":        None,
                "fret_correction":     None,
                "fingering_source":    None,
            })

    return results


# ---------------------------------------------------------------------------
# Closed-position preference
# ---------------------------------------------------------------------------

def _prefer_closed(voicings: list[dict]) -> list[dict]:
    """Keep one voicing per (category, inversion, omission) slot.

    Prefers fully-fretted (closed) shapes over open-string shapes. When
    multiple closed voicings exist for the same slot, keeps the lowest-fret one.
    """
    slots: dict[tuple, dict[str, list[dict]]] = defaultdict(lambda: {"closed": [], "open": []})
    for v in voicings:
        key = (v["category"], v["inversion_label"], tuple(v["omitted_chord_tones"]))
        has_open = any(n["fret"] == 0 for n in v["notes"])
        slots[key]["open" if has_open else "closed"].append(v)

    result: list[dict] = []
    for slot_vox in slots.values():
        candidates = slot_vox["closed"] if slot_vox["closed"] else slot_vox["open"]
        result.append(min(candidates, key=lambda v: v["starting_fret"]))
    return result


# ---------------------------------------------------------------------------
# Full and partial voicing builders
# ---------------------------------------------------------------------------

def _full_voicings(chord_type: str, root: str, groups: list[list[int]]) -> list[dict]:
    """Generate voicings using the complete chord tone set."""
    tones = _chord_tones_for(root, chord_type)
    result: list[dict] = []
    for group in groups:
        if len(group) == len(tones):
            result.extend(_generate_voicings(chord_type, group, tones, root))
    return result


def _partial_voicings(chord_type: str, root: str, groups: list[list[int]]) -> list[dict]:
    """Generate voicings with the root omitted (jazz rootless voicings).

    The omitted root is recorded in ``omitted_chord_tones``.
    """
    all_tones = _chord_tones_for(root, chord_type)
    subset = all_tones[1:]   # drop root, keep 3rd/5th/7th/9th
    result: list[dict] = []
    for group in groups:
        if len(group) == len(subset):
            result.extend(_generate_voicings(chord_type, group, subset, root))
    return result


# ---------------------------------------------------------------------------
# Transposition
# ---------------------------------------------------------------------------

def _transpose_to_root(diagrams: list[dict], target_root: str) -> list[dict]:
    """Transpose A-key diagrams to *target_root*."""
    a_idx = CHROMATIC.index("A")
    t_idx = CHROMATIC.index(target_root)
    delta = (t_idx - a_idx) % 12
    if delta > 6:
        delta -= 12
    result = [_transpose_diagram(d, delta, target_root) for d in diagrams]
    # Recalculate starting_fret from transposed frets (transpose may shift opens).
    for d in result:
        fretted = [n["fret"] for n in d["notes"] if n["fret"] > 0]
        if fretted:
            d["starting_fret"] = min(fretted)
    return result


# ---------------------------------------------------------------------------
# Main generation pipeline
# ---------------------------------------------------------------------------

def generate(output_dir: Path, quiet: bool = False) -> None:
    """Full generation pipeline.

    Generates A-key voicings, then transposes to all 12 chromatic roots.
    Writes one file per root per family (e.g. a_diminished.json).
    Also writes flat enharmonic copies (e.g. bb_diminished.json mirrors a#_diminished.json).
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: Generate A-key voicings for each chord type.
    a_diagrams: dict[str, list[dict]] = {}
    for family, chord_types in _FAMILIES.items():
        for chord_type in chord_types:
            n_tones = len(set(_CHORD_TONES[chord_type]))

            if n_tones == 3:
                # Triad: full voicings on 3-string groups only.
                full = _full_voicings(chord_type, "A", _GROUPS_3)
                partial: list[dict] = []

            elif n_tones == 4:
                # 7th chord: full on 4-string, partial (root omitted) on 3-string.
                full = _full_voicings(chord_type, "A", _GROUPS_4)
                partial = _partial_voicings(chord_type, "A", _GROUPS_3)

            elif n_tones == 5:
                # 5-note chord (aug9): partial (root omitted) on 4-string groups.
                full = []
                partial = _partial_voicings(chord_type, "A", _GROUPS_4)

            else:
                full = partial = []

            combined = _prefer_closed(full + partial)
            a_diagrams[chord_type] = combined

            if not quiet:
                n_open = sum(
                    1 for d in combined
                    if any(n["fret"] == 0 for n in d["notes"])
                )
                print(
                    f"  {chord_type}: {len(full)} full + {len(partial)} partial"
                    f" → {len(combined)} after dedup ({n_open} w/open strings) (A)"
                )

    # Step 2: Write one file per root per family.
    for root in _CHROMATIC_ROOTS:
        for family, chord_types in _FAMILIES.items():
            all_diagrams: list[dict] = []
            for chord_type in chord_types:
                if root == "A":
                    diagrams = [dict(d) for d in a_diagrams[chord_type]]
                else:
                    diagrams = _transpose_to_root(a_diagrams[chord_type], root)
                all_diagrams.extend(diagrams)

            for i, d in enumerate(all_diagrams):
                d["diagram_index"] = i

            out_name = f"{root.lower()}_{family}.json"
            (output_dir / out_name).write_text(
                json.dumps(all_diagrams, indent=2), encoding="utf-8"
            )

    # Step 3: Write flat enharmonic copies (same content, flat-key filename).
    _FLAT_ALIASES: dict[str, str] = {
        "a#": "bb", "c#": "db", "d#": "eb", "f#": "gb", "g#": "ab",
    }
    n_flat = 0
    for sharp, flat in _FLAT_ALIASES.items():
        for family in _FAMILIES:
            sharp_path = output_dir / f"{sharp}_{family}.json"
            flat_path  = output_dir / f"{flat}_{family}.json"
            if sharp_path.exists():
                flat_path.write_bytes(sharp_path.read_bytes())
                n_flat += 1

    if not quiet:
        n_files = len(_CHROMATIC_ROOTS) * len(_FAMILIES)
        print(f"Wrote {n_files} sharp + {n_flat} flat enharmonic files to {output_dir}/")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def _print_summary(output_dir: Path) -> None:
    totals: dict[str, dict[str, int]] = defaultdict(lambda: {"total": 0, "valid": 0})
    grand_total = grand_valid = 0

    for family in _FAMILIES:
        for path in sorted(output_dir.glob(f"*_{family}.json")):
            data = json.loads(path.read_text(encoding="utf-8"))
            for d in data:
                ct = d.get("chord_type") or "unknown"
                totals[ct]["total"] += 1
                totals[ct]["valid"] += int(d.get("valid", False))
            grand_total += len(data)
            grand_valid += sum(1 for d in data if d.get("valid"))

    n_files = sum(
        1 for f in _FAMILIES for _ in output_dir.glob(f"*_{f}.json")
    )
    print(f"\n{'='*50}")
    print(f"Generation summary")
    print(f"{'='*50}")
    print(f"  Files:   {n_files}")
    print(f"  Total:   {grand_total} diagrams")
    pct = grand_valid / grand_total * 100 if grand_total else 0
    print(f"  Valid:   {grand_valid} ({pct:.1f}%)")
    print(f"  Invalid: {grand_total - grand_valid}")
    print()
    print(f"  {'Chord type':<12}  {'Valid':>6}  {'Total':>6}  {'%':>5}")
    print(f"  {'-'*12}  {'-'*6}  {'-'*6}  {'-'*5}")
    for ct, counts in sorted(totals.items()):
        t, v = counts["total"], counts["valid"]
        p = f"{v/t*100:.0f}%" if t else "—"
        print(f"  {ct:<12}  {v:>6}  {t:>6}  {p:>5}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="generate_inversions.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--output", metavar="DIR", default="output",
        help="Output directory for generated JSON files (default: output/)",
    )
    parser.add_argument(
        "--summary", action="store_true",
        help="Print per-chord-type counts after generation",
    )
    parser.add_argument(
        "-q", "--quiet", action="store_true",
        help="Suppress progress output",
    )
    args = parser.parse_args(argv)

    output_dir = Path(args.output).resolve()
    generate(output_dir, quiet=args.quiet)

    if args.summary:
        _print_summary(output_dir)

    return 0


if __name__ == "__main__":
    sys.exit(main())
